version: '3.7'

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/myfolder/src

    ports:
      - 3000:3000

  my-database:
    platform: linux/arm64/v8
    image: mysql:latest
    environment:
      MYSQL_DATABASE: process.env.DB_NAME
      MYSQL_ROOT_PASSWORD: process.env.DB_PASSWORD
    ports:
      - 3306:3306

  my-redis:
    image: redis:latest
    ports:
      - 6379:6379
